### ISSUE TITLE
Install Eclipse Mars fails

### ISSUE THREAD

**Issue by meeximum** [DevBoost/CommentTemplate#6]
I got an error installing CommentTemplate from Eclipse Marketplace
Cannot complete the install because one or more required items could not be found. Software being installed: CommentTemplate 0.9.3.v201307191659 (de.devboost.commenttemplate.feature.group 0.9.3.v201307191659) Missing requirement: CommentTemplate 0.9.3.v201307191659 (de.devboost.commenttemplate.feature.group 0.9.3.v201307191659) requires 'org.emftext.language.java.feature.group 0.0.0' but it could not be found

also reported here
https://marketplace.eclipse.org/content/error/report/2797080

**Comment by mirkoseifert** [comment]
Some URLs in the list of associated sites were broken due to some recent reorganization of websites and server. This is fixed now. Thanks for reporting.

You might need to clean up your list of update sites in Eclipse before trying to install again. Remove the EMFText and JaMoPP URLs. They will be replaced by the new ones when you install CommentTemplate.
